# Project information
site_name: Friends of Toowong Cemetery
site_url: https://www.fotc.au
site_author: Friends of Toowong Cemetery Association Inc.
site_description: >-
  Friends of Toowong Cemetery is a volunteer group that discover and share the history and stories of Toowong Cemetery.
copyright: © 1994 — 2025 Friends of Toowong Cemetery Association Inc., unless noted otherwise. 

# Watch these extra directories for changes 
watch:
 - snippets

# Configuration
theme:
  language: en
  name: material
  logo: assets/fotc-logo.png
  favicon: favicon.ico
  font:
    text: Raleway
    code: Roboto Mono 
  palette:
    scheme: default
    primary: deep purple
    accent: purple
# toggle between alternate schemes
#    - scheme: default
#      primary: deep purple
#      accent: purple
#      toggle:
#        icon: octicons/sun-16
#        name: Switch to dark mode
#    - scheme: slate
#      primary: red
#      accent: deep orange
#      toggle:
#        icon: custom/ghost
#        name: Switch to light mode
  icon:
    admonition:
      question: fontawesome/solid/hand-holding-heart
      example: fontawesome/regular/compass
  custom_dir: overrides
  features:
# instant and announce seem to conflict with was this page helpful. Pick one. Works on Material for Mkdocs - look there. 
#    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
#    - navigation.footer
#    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tooltips
    - content.footnote.tooltips    
    - toc.follow

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:inquiries@fotc.au
      name: Email us
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/fotc.au
      name: Bluesky
#    - icon: fontawesome/brands/facebook
#      link: https://www.facebook.com/1871fotc/
#      name: Facebook @1871fotc
#    - icon: fontawesome/brands/youtube
#      link: https://www.youtube.com/@1871fotc
#      name: YouTube @1871fotc  
#    - icon: fontawesome/brands/github
#      link: https://github.com/1871fotc/1871fotc.github.io
#      name: Code, data and more on GitHub
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/1871fotc
#      name: Twitter @1871fotc

  analytics: 
    provider: google
    property: G-XDRM6G59W8
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks for your feedback! <br><b><a href="https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590={}" target=_blank>How we can improve?</a></b>

# Add feedback form for positive feedback
#         note: >-
#           Thanks for your feedback!<br><b><a href="https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590={}" target=_blank>What did we get right?</a></b>
#
#
# See https://support.google.com/a/users/answer/9308781?hl=en; add {} to URL answer; copy link; replace =%7B%7D with ={}; done            
# https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590=%7B%7D
#
#  consent:
#    title: Cookie consent
#    description: >-
#      <p>We use cookies to recognise your repeated visits, determine if you find what you're searching for, and measure if you think this site is helpful.</p>
#      <p>With your consent, you're helping us make this site better.</p>
  
extra_css:
  - stylesheets/extra.css

# Extensions  
markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 2
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde   
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta

# Sortable data table
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  
# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|\-(?!\d)|&[lg]t;'
#    separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
# - tags:
#      tags_file: tags.md
#      tags_allowed:
#        - Freemasons
#        - Ancient Order of Foresters
#  - optimize:
#      optimize_png: false
#      optimize_jpg: false
#      optimize_jpg_quality: 75
  - social:
      cards_layout: default/variant
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: true
      caption_position: bottom
  - redirects:
      redirect_maps:
        'home/home.md': 'index.md'
        'home/index.md': 'index.md'
        'walks/news.md': 'index.md'        
        'fotc/index.md': 'index.md'        
# set up redirects for renamed pages
#        'stories/in-their-caring-hands.md': 'stories/nurses-and-doctors.md'
#        'stories/jewish.md': 'walks/jewish-walk.md'
#        'stories/jewish-walk.md': 'walks/jewish-walk.md'
#        'stories/federation-walk.md.md': 'walks/federation-walk.md'
# set up redirects for deep links
        'walks/walks.md': 'walks/index.md'
        'activities/activities.md': 'about/index.md'
        'obituaries/obituaries.md': 'research/index.md'
        'publications/publications.md': 'about/publications.md'
        'membership/membership.md': 'about/index.md'
        'links/links.md': 'research/index.md'
        'contactus/contactus.md': 'contact.md'
# redirect to bitly to count QR code scans
        'hello.md': 'https://bit.ly/3wQYQxe'

# Page tree - only 2 levels allowed
nav:
  - Home: index.md
  - Cemetery History: history.md
  - Stories:
    - Stories: stories/index.md
# Politics
    - Queensland Governors: stories/governors.md
    - Brisbane Mayors: stories/brisbane-mayors.md
    - One Adult, One Vote: stories/suffrage.md
    - Labor Luminaries: stories/labor-luminaries.md
    - The Great Shearers' Strike: stories/shearers-strike.md
# Local stories    
    - Founding Fathers: stories/founding-fathers.md     
    - Notable Women: stories/notable-women.md    
    - Toowong Identities: stories/toowong-identities-1.md 
    - More Toowong Identities: stories/toowong-identities-2.md
#    - Toowong Streets: stories/toowong-street-name-origins.md
# Stories by Profession    
    - Artists: stories/artists.md 
    - Fire Fighters: stories/fire-fighters.md
    - Health Professionals: stories/nurses-and-doctors.md
    - Judiciary: stories/judiciary.md
    - Mariners: stories/anchors-aweigh.md
    - Monumental Masons: stories/monumental-masons.md
    - Performers: stories/all-the-worlds-a-stage.md 
    - Police: stories/police.md 
    - Print Media Identities: stories/printers.md
    - More Print Media Identities: stories/printers-2.md
    - Prospectors: stories/prospectors.md    
    - Sporting Personalities: stories/sporting-personalities.md
    - Railway People: stories/railway.md
    - Undertakers: stories/undertakers.md
# Military stories
    - Colonial Conflicts: stories/colonial-conflicts.md         
    - Lest We Forget: stories/lest-we-forget.md
    - Lest We Forget - Naval: stories/lest-we-forget-navy.md 
    - Men of the Royal Navy: stories/men-of-the-royal-navy.md
    - Scots in the AIF: stories/scots-in-the-aif-ww1.md
    - 1919 Soldiers: stories/1919-soldiers.md
    - Conflict and Compassion: stories/conflict-and-compassion.md
# Community stories  
    - The Irish: stories/irish.md 
    - The Lutheran: stories/lutheran.md
# Other themed stories 
    - Christmas Shopping 1877: stories/christmas-shopping-1877.md
    - The Other Half: stories/the-other-half.md
    - Steam: stories/steam.md
    - Building Brisbane: stories/brisbane-open-house.md   
    - Convicts: stories/convict-connections.md      
    - Erected by Family, Friends and Colleagues: stories/erected-by-friends.md    
    - Christmas: stories/christmas.md    
    - Weather: stories/weather.md 
#    - 1923: stories/1923.md
    - 20/20 Vision: stories/2020-vision.md
    - Rich man, Poor man: stories/rich-man-poor-man.md
    - Taken before their time: stories/taken-before-their-time.md  
    - Children: stories/children.md 
    - Mothers: stories/mothers.md
# Stories by Portion
    - Portion 5 - part 1: stories/portion5-part1.md
    - Portion 5 - part 2: stories/portion5-part2.md
    - Portion 6 and 24: stories/portion6-and-24.md
    - Portion 15 and 16: stories/portion15-and-16.md
  - Walks:   
    - Walks: walks/index.md 
    - The Federation Walk: walks/federation-walk.md
    - Dr. Lilian Cooper Walk: walks/lilian-cooper-walk.md 
    - The Jewish Walk: walks/jewish-walk.md 
#    - Mount Blackall Walk: walks/mount-blackall-walk.md
  - Guided Tours: guided-tours.md  
  - Headstones: 
    - Headstones: headstones/index.md  
    - Headstone Symbols: headstones/symbols.md
    - Headstone Signs: headstones/signs.md 
#    - Shapes: headstones/shapes.md  
#    - Monuments: headstones/monuments.md
    - Queensland's Oldest Headstones: headstones/queenslands-oldest-headstones.md
    - Archaeological Digs: headstones/archaeological-digs.md
    - Moved Paddington Cemetery Headstones: headstones/moved-paddington-headstones.md
    - Lost Paddington Cemetery Headstones: headstones/lost-paddington-headstones.md
#    - Lost Toowong Cemetery Headstones: headstones/lost-toowong-headstones.md
#    - At Risk Headstones: headstones/at-risk-headstones.md   
#    - Conserving Headstones: headstones/conserving-headstones.md
#    - Restored Headstones: headstones/restored-headstones.md
#    - Celebrity Headstones: headstones/celebrities.md
  - Research:
    - Research Resources: research/index.md
    - Find a Grave: research/find-a-grave.md  
    - Find a Story: research/find-a-story.md
#    - Paddington Cemetery: research/paddington-cemetery.md
    - Historic Maps: research/historic-maps.md
    - Data: research/data.md
  - About Us: 
    - About Us: about/index.md
    - Publications: about/publications.md
    - Extraordinary Stories of Ordinary People: about/extraordinary-stories.md
    - 140th Anniversary Commemoration: about/140-commemoration.md
    - Federation Pavilion: about/federation-pavilion.md
    - Information Signs: about/information-signs.md
    - Legal: about/legal.md
  - Contact Us: contact.md
